package gosyga

import (
	"encoding/json"
	"fmt"
	"net/url"
)

//
// TODO: replace this file with swagger autogenerated code?
//

type AdminApi struct {
	bucket string
	url    string
}

type User struct {
	Name          string   `json:"name"`
	Password      string   `json:"password,omitempty"`
	AdminChannels []string `json:"admin_channels"`
	AllChannels   []string `json:"all_channels"`
	AdminRoles    []string `json:"admin_roles"`
	Email         string   `json:"email,omitempty"`
	Disabled      bool     `json:"disabled"`
}

type SessionRequest struct {
	UserName string `json:"name"`
	TTL      int    `json:"ttl"`
}

type SessionResponse struct {
	CookieName string `json:"cookie_name"`
	Expires    string `json:"expires"`
	SessionId  string `json:"session_id"`
}

func NewAdminApi(url string, bucket string) *AdminApi {
	return &AdminApi{
		bucket: bucket,
		url:    url,
	}
}

func (d *AdminApi) GetUser(uuid string) (*User, error) {
	url := d.url + "/" + url.QueryEscape(d.bucket) + "/_user/" + url.QueryEscape(uuid)

	resp, err := Do_GET(url)

	if err != nil {
		return nil, err
	}

	if resp.Code == 404 {
		return nil, nil // user doesn't exists in database
	}

	var user User
	err = json.Unmarshal(resp.Body, &user)

	if err != nil {
		return nil, err
	}

	return &user, nil
}

func (d *AdminApi) CreateUser(uuid string, password string) (*User, error) {
	url := d.url + "/" + url.QueryEscape(d.bucket) + "/_user/"
	fmt.Println("CreateUser:>", url)

	user := User{
		Name:     uuid,
		Password: password,
		Disabled: false,
	}

	data, err := json.Marshal(user)

	if err != nil {
		return nil, err
	}

	_, err = Do_POST(url, data)

	if err != nil {
		return nil, err
	}

	return d.GetUser(uuid)
}

func (d *AdminApi) CreateSession(username string) (*SessionResponse, error) {
	url := d.url + "/" + url.QueryEscape(d.bucket) + "/_session"

	sessReq := SessionRequest{
		UserName: username,
		TTL:      24 * 3600, // 24 hours
	}

	data, err := json.Marshal(sessReq)
	if err != nil {
		return nil, err
	}

	resp, err := Do_POST(url, data)

	if err != nil {
		return nil, err
	}

	var sessionResp SessionResponse
	err = json.Unmarshal(resp.Body, &sessionResp)

	if err != nil {
		return nil, err
	}

	return &sessionResp, nil
}
